name: Update Last Updated

on:
  push:
    paths:
      - 'github.json'
      - 'forum.json'
  workflow_dispatch: 

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Update index.html
      run: python update.py

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add index.html
        git commit -m "Update last updated date in index.html"
        git push

    - name: Deploy to GitHub Pages
      uses: actions-gh-pages@v4
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        folder: ./
